#!/bin/zsh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SIGNING_IDENTITY_NAME="${REMOTELY_SIGNING_IDENTITY:-remotely Local Signing}"
LOGIN_KEYCHAIN="$HOME/Library/Keychains/login.keychain-db"

find_valid_identity_hash() {
  security find-identity -v -p codesigning 2>/dev/null \
    | awk -v name="$SIGNING_IDENTITY_NAME" '$0 ~ ("\"" name "\"") { print $2; exit }'
}

find_matching_identity_hash() {
  security find-identity -p codesigning 2>/dev/null \
    | awk -v name="$SIGNING_IDENTITY_NAME" '$0 ~ ("\"" name "\"") { print $2; exit }'
}

if ! command -v security >/dev/null 2>&1; then
  echo "security is not available. A macOS Keychain is required for stable code signing." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is not available. Install the Xcode Command Line Tools or OpenSSL before building remotely." >&2
  exit 1
fi

VALID_IDENTITY="$(find_valid_identity_hash)"
if [[ -n "$VALID_IDENTITY" ]]; then
  echo "Stable signing identity already exists: $SIGNING_IDENTITY_NAME ($VALID_IDENTITY)"
  exit 0
fi

if [[ ! -f "$LOGIN_KEYCHAIN" ]]; then
  LOGIN_KEYCHAIN="$(security default-keychain -d user | tr -d '"')"
fi
if [[ -z "$LOGIN_KEYCHAIN" || ! -f "$LOGIN_KEYCHAIN" ]]; then
  echo "Could not locate the user's login Keychain." >&2
  exit 1
fi

umask 077
TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/remotely-signing.XXXXXX")"
trap 'rm -rf "$TEMP_DIR"' EXIT HUP INT TERM

KEY_FILE="$TEMP_DIR/remotely-signing.key.pem"
CSR_FILE="$TEMP_DIR/remotely-signing.csr.pem"
CERT_FILE="$TEMP_DIR/remotely-signing.cert.pem"
EXISTING_CERT_FILE="$TEMP_DIR/remotely-existing.cert.pem"
P12_FILE="$TEMP_DIR/remotely-signing.identity.p12"
OPENSSL_CONFIG="$TEMP_DIR/openssl.cnf"

certificate_is_ours() {
  local cert="$1"
  [[ -s "$cert" ]] || return 1

  local subject issuer eku
  subject="$(openssl x509 -in "$cert" -noout -subject -nameopt RFC2253 2>/dev/null || true)"
  issuer="$(openssl x509 -in "$cert" -noout -issuer -nameopt RFC2253 2>/dev/null || true)"
  eku="$(openssl x509 -in "$cert" -noout -text 2>/dev/null || true)"

  [[ "$subject" == *"CN=$SIGNING_IDENTITY_NAME"* ]] || return 1
  [[ "$subject" == *"O=remotely"* ]] || return 1
  [[ "$subject" == *"OU=Local Code Signing"* ]] || return 1
  [[ "${subject#subject=}" == "${issuer#issuer=}" ]] || return 1
  [[ "$eku" == *"Code Signing"* ]] || return 1
  return 0
}

# v1.9.23 could successfully import the identity and then fail while applying
# trust. Preserve that identity if possible: trust the self-signed certificate
# as an actual root for the Code Signing policy and re-check validity.
MATCHING_IDENTITY="$(find_matching_identity_hash)"
if [[ -n "$MATCHING_IDENTITY" ]] && security find-certificate -c "$SIGNING_IDENTITY_NAME" -p "$LOGIN_KEYCHAIN" > "$EXISTING_CERT_FILE" 2>/dev/null; then
  if certificate_is_ours "$EXISTING_CERT_FILE"; then
    echo "Found incomplete remotely signing identity; repairing Code Signing trust..."
    if security add-trusted-cert \
      -r trustRoot \
      -p codeSign \
      -k "$LOGIN_KEYCHAIN" \
      "$EXISTING_CERT_FILE"; then
      VALID_IDENTITY="$(find_valid_identity_hash)"
      if [[ -n "$VALID_IDENTITY" ]]; then
        echo "Stable signing identity repaired: $SIGNING_IDENTITY_NAME ($VALID_IDENTITY)"
        exit 0
      fi
    fi

    # No remotely build could have been signed after the v1.9.23 setup failure.
    # If this exact self-signed identity is still invalid, remove only that
    # incomplete identity so it can be regenerated correctly below.
    echo "Incomplete remotely signing identity is still invalid; regenerating it as a Self Signed Root..."
    security delete-identity -c "$SIGNING_IDENTITY_NAME" "$LOGIN_KEYCHAIN" >/dev/null 2>&1 || true
  else
    cat >&2 <<EOF_FOREIGN
A code-signing identity named "$SIGNING_IDENTITY_NAME" exists but is not the identity generated by remotely.

remotely will not replace it automatically. Rename/remove that identity or set REMOTELY_SIGNING_IDENTITY to a different persistent code-signing identity.
EOF_FOREIGN
    exit 1
  fi
elif security find-certificate -c "$SIGNING_IDENTITY_NAME" -p "$LOGIN_KEYCHAIN" > "$EXISTING_CERT_FILE" 2>/dev/null; then
  # A certificate without a matching private-key identity can also be residue
  # from an interrupted setup. Only clean it automatically when its subject and
  # purpose prove it was generated by remotely.
  if certificate_is_ours "$EXISTING_CERT_FILE"; then
    echo "Removing incomplete remotely signing certificate from an earlier failed setup..."
    security delete-certificate -c "$SIGNING_IDENTITY_NAME" "$LOGIN_KEYCHAIN" >/dev/null 2>&1 || true
  else
    cat >&2 <<EOF_STALE
A certificate named "$SIGNING_IDENTITY_NAME" already exists, but it is not a usable remotely code-signing identity.

remotely will not overwrite an unrelated certificate automatically.
EOF_STALE
    exit 1
  fi
fi

cat > "$OPENSSL_CONFIG" <<EOF_CONFIG
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = remotely_dn

[ remotely_dn ]
CN = $SIGNING_IDENTITY_NAME
O = remotely
OU = Local Code Signing

[ codesign ]
# Match Keychain Access' "Self Signed Root" + "Code Signing" model. Because
# this certificate is its own trust anchor, it must actually be a CA/root.
basicConstraints = critical,CA:TRUE,pathlen:0
keyUsage = critical,digitalSignature,keyCertSign
extendedKeyUsage = critical,codeSigning
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
EOF_CONFIG

echo "Creating persistent local signing identity: $SIGNING_IDENTITY_NAME"
openssl genrsa -out "$KEY_FILE" 2048 >/dev/null 2>&1
openssl req -new \
  -key "$KEY_FILE" \
  -out "$CSR_FILE" \
  -config "$OPENSSL_CONFIG"
openssl x509 -req \
  -sha256 \
  -days 3650 \
  -in "$CSR_FILE" \
  -signkey "$KEY_FILE" \
  -out "$CERT_FILE" \
  -extfile "$OPENSSL_CONFIG" \
  -extensions codesign

# Verify that the generated certificate really is the Self Signed Root we
# intended before importing anything into Keychain.
openssl x509 -in "$CERT_FILE" -noout -text | grep -q 'CA:TRUE' || {
  echo "Generated signing certificate is not a Self Signed Root; refusing to import it." >&2
  exit 1
}

# OpenSSL 3 changed PKCS#12 export defaults to AES/PBKDF2 with a SHA-256 MAC.
# Use established PKCS#12 transport algorithms for macOS Security.framework
# interoperability. The certificate/key remain RSA-2048/SHA-256; these settings
# protect only the short-lived transfer container.
P12_PASSWORD="$(openssl rand -hex 24)"
openssl pkcs12 -export \
  -name "$SIGNING_IDENTITY_NAME" \
  -inkey "$KEY_FILE" \
  -in "$CERT_FILE" \
  -out "$P12_FILE" \
  -keypbe PBE-SHA1-3DES \
  -certpbe PBE-SHA1-3DES \
  -macalg sha1 \
  -passout pass:"$P12_PASSWORD"

openssl pkcs12 \
  -in "$P12_FILE" \
  -noout \
  -passin pass:"$P12_PASSWORD" >/dev/null 2>&1

echo "Importing signing identity into login Keychain..."
security import "$P12_FILE" \
  -k "$LOGIN_KEYCHAIN" \
  -P "$P12_PASSWORD" \
  -T /usr/bin/codesign >/dev/null
unset P12_PASSWORD

# A locally generated Self Signed Root is not an Apple-trusted certificate.
# Trust only this root and only for Code Signing. security may present the
# normal macOS authentication dialog when changing per-user Trust Settings.
echo "Applying Code Signing trust to local root certificate..."
security add-trusted-cert \
  -r trustRoot \
  -p codeSign \
  -k "$LOGIN_KEYCHAIN" \
  "$CERT_FILE"

VALID_IDENTITY="$(find_valid_identity_hash)"
if [[ -z "$VALID_IDENTITY" ]]; then
  cat >&2 <<EOF_FAIL
The certificate and private key were imported, but macOS still does not report "$SIGNING_IDENTITY_NAME" as a valid Code Signing identity.

The build will not fall back to ad-hoc signing. Inspect the certificate/private key in the login Keychain and rerun ./build.sh after resolving the trust prompt.
EOF_FAIL
  exit 1
fi

echo "Stable signing identity ready: $SIGNING_IDENTITY_NAME ($VALID_IDENTITY)"
